# Generated by Django 5.2.1 on 2025-10-07 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderGarbagesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garbage_amount', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('garbage_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.garbagedata')),
            ],
        ),
        migrations.CreateModel(
            name='OrdersData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_map_lat_location', models.FloatField(blank=True, null=True)),
                ('order_map_lng_location', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('order_garbages_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders_app.ordergarbagesdata')),
                ('user_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
