# Generated by Django 5.2.1 on 2025-10-07 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersdata',
            name='access_token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
