# Generated by Django 5.2.1 on 2025-10-10 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0002_ordersdata_access_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordersdata',
            name='order_garbages_data',
        ),
        migrations.AddField(
            model_name='ordergarbagesdata',
            name='order_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders_app.ordersdata'),
        ),
    ]
