# Generated by Django 5.2.1 on 2025-10-15 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0003_remove_ordersdata_order_garbages_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersdata',
            name='order_from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordersdata',
            name='order_to_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
