# Generated by Django 5.2.1 on 2025-10-15 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0004_ordersdata_order_from_date_ordersdata_order_to_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersdata',
            name='created_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
