# Generated by Django 5.2.1 on 2025-10-16 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0005_ordersdata_created_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordergarbagesdata',
            name='garbage_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
