# Generated by Django 5.2.1 on 2025-10-16 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0006_alter_ordergarbagesdata_garbage_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersdata',
            name='order_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
