# Generated by Django 5.2.1 on 2025-10-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0007_ordersdata_order_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersdata',
            name='order_status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
