# Generated by Django 5.2.5 on 2025-11-05 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0008_ordersdata_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordersdata',
            old_name='order_from_date',
            new_name='order_date',
        ),
        migrations.RemoveField(
            model_name='ordersdata',
            name='order_to_date',
        ),
        migrations.AddField(
            model_name='ordersdata',
            name='order_from_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordersdata',
            name='order_to_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
