# Generated by Django 5.2.5 on 2025-11-05 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0009_rename_order_from_date_ordersdata_order_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordersdata',
            old_name='description',
            new_name='address',
        ),
    ]
