# Generated by Django 5.2.5 on 2025-11-06 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0011_selectedaddressdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectedaddressdata',
            name='coords_lat',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='selectedaddressdata',
            name='coords_lng',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
