# Generated by Django 5.2.5 on 2025-11-06 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0012_selectedaddressdata_coords_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersdata',
            name='delete_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
