# Generated by Django 5.2.5 on 2025-11-06 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0013_ordersdata_delete_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersdata',
            name='delete_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
