# Generated by Django 5.2.5 on 2025-11-06 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0014_ordersdata_delete_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectedaddressdata',
            name='address_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
