# Generated by Django 5.2.5 on 2025-11-06 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0015_selectedaddressdata_address_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersdata',
            name='order_map_image',
            field=models.ImageField(blank=True, null=True, upload_to='map_images'),
        ),
    ]
