# Generated by Django 5.2.5 on 2025-11-06 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0016_ordersdata_order_map_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordersdata',
            name='order_map_image',
        ),
    ]
