# Generated by Django 5.2.5 on 2025-11-28 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0017_remove_ordersdata_order_map_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordergarbagesdata',
            name='description',
        ),
    ]
