# Generated by Django 5.2.1 on 2025-10-13 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SourcesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kavenegar_access_hash', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
