# Generated by Django 5.2.1 on 2025-10-17 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel_app', '0001_initial'),
        ('wallet_app', '0003_walletsdata_sheba_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('withdrawal_amount', models.IntegerField(blank=True, null=True)),
                ('wallet_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet_app.walletsdata')),
            ],
        ),
    ]
