# Generated by Django 5.2.5 on 2025-10-22 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel_app', '0002_withdrawalsdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalsdata',
            name='request_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
