# Generated by Django 5.2.5 on 2025-10-22 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel_app', '0003_withdrawalsdata_request_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalsdata',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
