# Generated by Django 5.2.5 on 2025-10-25 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel_app', '0004_withdrawalsdata_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationMessagesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.CharField(blank=True, max_length=200, null=True)),
                ('message_send', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
