# Generated by Django 5.2.5 on 2025-11-26 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel_app', '0005_operationmessagesdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawalsdata',
            name='status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
