# Generated by Django 5.2.5 on 2025-11-28 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel_app', '0006_alter_withdrawalsdata_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalsdata',
            name='pay_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
