# Generated by Django 5.2.1 on 2025-10-17 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletsdata',
            name='inventory',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
