# Generated by Django 5.2.1 on 2025-10-17 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_app', '0002_alter_walletsdata_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletsdata',
            name='sheba_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
