# Generated by Django 5.2.1 on 2025-10-13 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateNewUserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_phone_number', models.CharField(blank=True, max_length=200, null=True)),
                ('user_random_code', models.CharField(blank=True, max_length=200, null=True)),
                ('send_time', models.DateTimeField(blank=True, null=True)),
                ('try_count', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='usersdata',
            name='profile_image',
        ),
    ]
