# Generated by Django 5.2.5 on 2025-10-19 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_createnewuserdata_remove_usersdata_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersdata',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
