# Generated by Django 5.2.5 on 2025-10-20 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_userpermissions_usersdata_admin_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='user_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
