# Generated by Django 5.2.5 on 2025-10-26 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_userpermissions_user_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersdata',
            name='device_token',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
