# Generated by Django 5.2.5 on 2025-10-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0006_usersdata_device_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersdata',
            name='master_of_admins',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
