# Generated by Django 5.2.5 on 2025-11-17 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0007_usersdata_master_of_admins'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersdata',
            name='identification_code',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
