# Generated by Django 5.2.5 on 2025-11-17 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0008_usersdata_identification_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersdata',
            old_name='identification_code',
            new_name='my_identification_code',
        ),
        migrations.AddField(
            model_name='usersdata',
            name='set_identification_code',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
