# Generated by Django 5.2.5 on 2025-11-17 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0009_rename_identification_code_usersdata_my_identification_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersdata',
            name='birth_day',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usersdata',
            name='gender',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
