# Generated by Django 5.2.1 on 2025-10-07 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='garbagedata',
            old_name='price',
            new_name='price_per_unit',
        ),
    ]
