# Generated by Django 5.2.1 on 2025-10-16 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_price_garbagedata_price_per_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garbagedata',
            name='price_per_unit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
