# Generated by Django 5.2.5 on 2025-11-26 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_garbagedata_price_per_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garbagedata',
            name='garbage_categories_data',
        ),
    ]
