# Generated by Django 5.2.5 on 2025-11-26 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_garbagedata_garbage_categories_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garbagedata',
            name='units_of_measurement_data',
        ),
    ]
