# Generated by Django 5.2.5 on 2025-11-26 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_garbagedata_units_of_measurement_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='garbagedata',
            name='units_of_measurement_data',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
