# Generated by Django 5.2.5 on 2025-12-09 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_garbagedata_units_of_measurement_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='garbagedata',
            name='garbage_icon',
            field=models.ImageField(blank=True, null=True, upload_to='garbage_icons'),
        ),
        migrations.AddField(
            model_name='garbagedata',
            name='garbage_image',
            field=models.ImageField(blank=True, null=True, upload_to='garbage_images'),
        ),
    ]
